# Generated by Django 4.2.5 on 2023-09-28 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('images', models.CharField(blank=True, max_length=500, null=True)),
                ('availability', models.CharField(blank=True, max_length=500, null=True)),
                ('sku', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='abc.jpg', null=True, upload_to='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='Homepage.productsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('total', models.CharField(blank=True, max_length=500, null=True)),
                ('order_date', models.DateField(blank=True, max_length=500, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('checkout', models.BooleanField(default=False)),
                ('ordered', models.CharField(blank=True, max_length=500, null=True)),
                ('order_status', models.CharField(blank=True, max_length=500, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=500, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=500, null=True)),
                ('shipment_tracking_information', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
