# Generated by Django 4.2.2 on 2023-07-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsmodel',
            name='admin_feedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
